server.servlet.context-path=/auth-service
server.port=8082
spring.application.name=auth-service
spring.sleuth.messaging.jms.enabled=false



# JWT
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Database
db.host=localhost
db.port=5432
db.name=user_db

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/${db.name}
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.connection-test-query=SELECT 1

# Redis
redis.host=127.0.0.1
redis.port=6379
redis.password=
redis.database=0

# RabbitMQ Connection
spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=123abc
spring.rabbitmq.virtual-host=/

# Auto declare
spring.rabbitmq.dynamic=true

# Optional debug
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true

# Custom exchange config
rabbitmq.exchange=user.exchange
rabbitmq.routing-key=user.created
rabbitmq.queue=user.created.queue




